# SAMPLE
development:
   adapter: postgresql
   database: restapi_development
   username: postgres
   password: password
   port: 5435
   host: localhost

test:
   adapter: postgresql
   database: restapi_test
   username: postgres
   password: password
   port: 5435
   host: localhost
   
production:
   adapter: postgresql
   database: restapi_production
   username: postgres
   password: password
   port: 5435
   host: localhost